---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    helm.sh/resource-policy: keep
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/gce-pd
  name: puppet-code
  namespace: puppet
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gold
  volumeMode: Filesystem
